#!/bin/bash
#
#Author: John Britto.
#Description: This script rely on the logs generated by the ESXi host in its /vmfs/volumes/backup/logs/  directory.  
#             This script parse the log file and send email based on the log status. because email client is nat available in ESXi host.
YMD=$(date +%Y-%m-%d)        # date now eg: 2015-03-26
YM=$(date +%Y-%m)   		 # date now eg: 2015-03
DOW=$(date +%u)              # Day number of the week 1 to 7 where 1 represents Monday
DOM=$(date +%d)              # Date of the Month e.g. 27
MN=$(date +%m)				 # Month Number e.g 01...12
DOWEEKLY_ON=6
DOMONTHLY_ON=01
TREE="$(which tree)"

VM_DAILY_LOG_PATH=/mnt/nfs-backup/logs/vm_daily_logs
VM_WEEK_LOG_PATH=/mnt/nfs-backup/logs/vm_week_logs
VM_MONTH_LOG_PATH=/mnt/nfs-backup/logs/vm_month_logs

VM_DAILY_LOG_FILE=$(find "$VM_DAILY_LOG_PATH" -name *"${YMD}"*)
VM_WEEKLY_LOG_FILE=$(find "$VM_WEEK_LOG_PATH" -name *"${YMD}_${DOWEEKLY_ON}"*)
VM_MONTHLY_LOG_FILE=$(find "$VM_MONTH_LOG_PATH" -name *"${YM}-${DOMONTHLY_ON}"*)

A_EMAIL=dailymonitoring@sodexis.com
CC1=john@sodexis.com

vm_daily_mail () {
cd $VM_DAILY_LOG_PATH
if [ -f "${VM_DAILY_LOG_FILE}" ]; then
    sed -i '/Clone:/d' ${VM_DAILY_LOG_FILE} 
    echo " " >> ${VM_DAILY_LOG_FILE}
    echo -e "$(yes '=' | head -75 | paste -s -d '' -)" >> ${VM_DAILY_LOG_FILE}
    echo "Stored Files are:" >> ${VM_DAILY_LOG_FILE}
    echo " " >> ${VM_DAILY_LOG_FILE}
    $TREE -h /mnt/nfs-backup/VM_Backups_Daily >> ${VM_DAILY_LOG_FILE}
    echo " " >> ${VM_DAILY_LOG_FILE}
    echo -e "$(yes '=' | head -75 | paste -s -d '' -)" >> ${VM_DAILY_LOG_FILE}
fi	
if [ ! -f "${VM_DAILY_LOG_FILE}" ]; then
	echo -e "The VM Daily log file is missing." | mail -s "ERROR - VM's Daily Backup" -c "$CC1" "$A_EMAIL"
elif grep -oq 'Final status: OK, only a dryrun.' $VM_DAILY_LOG_FILE; then
	mail -s "OK - VM's Daily Backup - DRY RUN" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
elif grep -oq 'Final status: All VMs backed up OK!'	$VM_DAILY_LOG_FILE; then
	mail -s "SUCCESS - VM's Daily Backup" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
elif grep -oq 'Final status: WARNING: All VMs backed up, but some disk(s) failed!' $VM_DAILY_LOG_FILE; then
    mail -s "WARNING - VM's Daily Backup" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
elif grep -oq 'Final status: ERROR: Only some of the VMs backed up!' $VM_DAILY_LOG_FILE; then
    mail -s "FAILURE - VM's Daily Backup" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
elif grep -oq 'Final status: ERROR: Only some of the VMs backed up, and some disk(s) failed!' $VM_DAILY_LOG_FILE; then
    mail -s "FAILURE - VM's Daily Backup" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
elif grep -oq 'Final status: ERROR: All VMs failed!' $VM_DAILY_LOG_FILE; then
    mail -s "FAILURE - VM's Daily Backup" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
elif grep -oq 'Final status: ERROR: No VMs backed up!' $VM_DAILY_LOG_FILE; then
    mail -s "FAILURE - VM's Daily Backup" -c "$CC1" "$A_EMAIL" < $VM_DAILY_LOG_FILE
fi
}

vm_weekly_mail () {
cd $VM_WEEKLY_LOG_PATH
if [ -f "${VM_WEEKLY_LOG_FILE}" ]; then
    sed -i '/Clone:/d' ${VM_WEEKLY_LOG_FILE} 
    echo " " >> ${VM_WEEKLY_LOG_FILE}
    echo -e "$(yes '=' | head -75 | paste -s -d '' -)" >> ${VM_WEEKLY_LOG_FILE}
    echo "Stored Files are:" >> ${VM_WEEKLY_LOG_FILE}
    echo " " >> ${VM_WEEKLY_LOG_FILE}
    $TREE -h /mnt/nfs-backup/VM_Backups_Weekly >> ${VM_WEEKLY_LOG_FILE}
    echo " " >> ${VM_WEEKLY_LOG_FILE}
    echo -e "$(yes '=' | head -75 | paste -s -d '' -)" >> ${VM_WEEKLY_LOG_FILE}
fi  
if [ "$DOW" -eq "$DOWEEKLY_ON" ]; then
    if [ ! -f "$VM_WEEKLY_LOG_FILE" ]; then
    	echo "The VM Weekly log file is missing." | mail -s "ERROR - VM's Weekly Backup" -c "$CC1" "$A_EMAIL"
    elif grep -oq 'Final status: OK, only a dryrun.' $VM_WEEKLY_LOG_FILE; then
    	mail -s "OK - VM's Weekly Backup - DRY RUN" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    elif grep -oq 'Final status: All VMs backed up OK!'	$VM_WEEKLY_LOG_FILE; then
    	mail -s "SUCCESS - VM's Weekly Backup" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    elif grep -oq 'Final status: WARNING: All VMs backed up, but some disk(s) failed!' $VM_WEEKLY_LOG_FILE; then
        mail -s "WARNING - VM's Weekly Backup" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: Only some of the VMs backed up!' $VM_WEEKLY_LOG_FILE; then
        mail -s "FAILURE - VM's Weekly Backup" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: Only some of the VMs backed up, and some disk(s) failed!' $VM_WEEKLY_LOG_FILE; then
        mail -s "FAILURE - VM's Weekly Backup" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: All VMs failed!' $VM_WEEKLY_LOG_FILE; then
        mail -s "FAILURE - VM's Weekly Backup" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: No VMs backed up!' $VM_WEEKLY_LOG_FILE; then
        mail -s "FAILURE - VM's Weekly Backup" -c "$CC1" "$A_EMAIL" < $VM_WEEKLY_LOG_FILE
    fi
fi
}

vm_monthly_mail () {
cd $VM_MONTHLY_LOG_PATH
if [ "$DOM" -eq "$DOMONTHLY_ON" ]; then
    if [ ! -f "$VM_MONTHLY_LOG_FILE" ]; then
    	echo "The VM Monthlylog file is missing." | mail -s "ERROR - VM's Monthly Backup" -c "$CC1" "$A_EMAIL"
    elif grep -oq 'Final status: OK, only a dryrun.' $VM_MONTHLY_LOG_FILE; then
    	mail -s "OK - VM's Monthly Backup - DRY RUN" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    elif grep -oq 'Final status: All VMs backed up OK!'	$VM_MONTHLY_LOG_FILE; then
    	mail -s "SUCCESS - VM's Monthly Backup" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    elif grep -oq 'Final status: WARNING: All VMs backed up, but some disk(s) failed!' $VM_MONTHLY_LOG_FILE; then
        mail -s "WARNING - VM's Monthly Backup" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: Only some of the VMs backed up!' $VM_MONTHLY_LOG_FILE; then
        mail -s "FAILURE - VM's Monthly Backup" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: Only some of the VMs backed up, and some disk(s) failed!' $VM_MONTHLY_LOG_FILE; then
        mail -s "FAILURE - VM's Monthly Backup" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: All VMs failed!' $VM_MONTHLY_LOG_FILE; then
        mail -s "FAILURE - VM's Monthly Backup" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    elif grep -oq 'Final status: ERROR: No VMs backed up!' $VM_MONTHLY_LOG_FILE; then
        mail -s "FAILURE - VM's Monthly Backup" -c "$CC1" "$A_EMAIL" < $VM_MONTHLY_LOG_FILE
    fi
fi
}

vm_daily_mail
vm_weekly_mail
#vm_monthly_mail

# Clean up Logfile
find "$VM_DAILY_LOG_PATH"/*.log -type f -mtime +3 -exec rm -f {} +
find "$VM_WEEK_LOG_PATH"/*.log -type f -mtime +3 -exec rm -f {} +

exit 0