# Backup script generated by Areca v7.4.6 on Oct 15, 2014 7:28 AM

# Full backup
# Target Group : "VM_Weekly_Backups"
# Target : "Home"
"/var/app/areca/bin/areca_cl.sh" backup -f -c -wdir "/var/app/areca/tmp" -config "/home/admin/.areca/workspace/VM_Weekly_Backups/1810574857.bcfg" -title "Home"

