# Script generated by Areca v7.4.6 on Oct 11, 2014 2:46 AM

# Target Group : "Websites-DB"
# Target : "Websites & DB"

# This script must be run every 7 days.

# Merge between day 7 and day 14 
"/var/app/areca/bin/areca_cl.sh" merge -c -config "/home/admin/.areca/workspace/Websites-DB/977679628.bcfg" -from 14 -to 7
