# Script generated by Areca v7.4.6 on Oct 11, 2014 2:46 AM

# Target Group : "Websites-DB"
# Target : "Websites & DB"

# This script must be run every 28 days.

# Merge between day 28 and day 56 
"/var/app/areca/bin/areca_cl.sh" merge -c -config "/home/admin/.areca/workspace/Websites-DB/977679628.bcfg" -from 56 -to 28

# Merge after day 168 
"/var/app/areca/bin/areca_cl.sh" merge -c -config "/home/admin/.areca/workspace/Websites-DB/977679628.bcfg" -delay 168
