# Backup script generated by Areca v7.4.6 on Oct 11, 2014 2:09 AM

# Full backup
# Target Group : "VM_Weekly_Backups"
# Target : "NagiosXI VM"
"/var/app/areca/bin/areca_cl.sh" backup -f -c -wdir "/var/app/areca/tmp" -config "/home/admin/.areca/workspace/VM_Weekly_Backups/334118795.bcfg" -title "NagiosXI VM"

