# Script generated by Areca v7.4.6 on Oct 11, 2014 2:46 AM

# Target Group : "Websites-DB"
# Target : "Websites & DB"

# This script must be run every day.

# Daily backup
"/var/app/areca/bin/areca_cl.sh" backup -c -wdir "/var/app/areca/tmp" -config "/home/admin/.areca/workspace/Websites-DB/977679628.bcfg" -title "Websites-DB"
