# Backup script generated by Areca v7.4.6 on Oct 11, 2014 2:08 AM

# Full backup
# Target Group : "VM_Daily_Backups"
# Target : "Sourceforge-1 VM"
"/var/app/areca/bin/areca_cl.sh" backup -f -c -wdir "/var/app/areca/tmp" -config "/home/admin/.areca/workspace/VM_Daily_Backups/1396543445.bcfg" -title "Sourceforge-1 VM"

