# Backup script generated by Areca v7.4.6 on Oct 11, 2014 2:07 AM

# Full backup
# Target Group : "VM_Daily_Backups"
# Target : "Sourceforge VM"
"/var/app/areca/bin/areca_cl.sh" backup -f -c -wdir "/var/app/areca/tmp" -config "/home/admin/.areca/workspace/VM_Daily_Backups/1366160921.bcfg" -title "Sourceforge VM"

